archives:
  - id: archive
    name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
builds:
  - goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - windows
      - linux
    main: ./cmd/pulumi-resource-frontegg
    binary: pulumi-resource-frontegg
    ldflags:
      - -X main.version={{.Tag}}
changelog:
  skip: true
